
test_energies: test_energies.cpp
	g++-11 -o test_energies -fopenmp -O3 test_energies.cpp

test_energies2: test_energies2.cpp
	g++-11 -o test_energies2 -O3 test_energies2.cpp

step_len_comp: step_len_comp.cpp
	g++-11 -o step_len_comp -fopenmp -O3 step_len_comp.cpp

dt_comp: dt_comp.cpp
	g++-11 -o dt_comp -fopenmp -O3 dt_comp.cpp
	
gradient_descent: gradient_descent.cpp
	g++-11 -o gradient_descent -O3 gradient_descent.cpp

interaction: interaction.cpp
	g++-11 -o interaction -fopenmp -O3 interaction.cpp
