
test_energies: test_energies.cpp
	g++-11 -o test_energies -fopenmp -O3 212536736.cpp

step_len_comp: step_len_comp.cpp
	g++-11 -o step_len_comp -fopenmp -O3 step_len_comp.cpp

dt_comp: dt_comp.cpp
	g++-11 -o dt_comp -fopenmp -O3 dt_comp.cpp
	

